services:

    Claroline\CoreBundle\Subscriber\SecurityEventSubscriber:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@http_client'
            - '@security.helper'
            - '@request_stack'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    Claroline\CoreBundle\Subscriber\FunctionalEventSubscriber:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }
